export enum EPermission {
    ADD_USERS = "ADD_USERS",
    REMOVE_USERS = "REMOVE_USERS",
    DEACTIVATE_USERS = "DEACTIVATE_USERS",
    EDIT_USERS = "EDIT_USERS",
    ADD_BOOKS = "ADD_BOOKS",
    EDIT_BOOKS = "EDIT_BOOKS",
    REMOVE_BOOKS = "REMOVE_BOOKS",
}