export enum EPermission {
    ADD_ALL_USERS = "ADD_ALL_USERS",
    REMOVE_ALL_USERS = "REMOVE_ALL_USERS",
    DEACTIVATE_ALL_USERS = "DEACTIVATE_ALL_USERS",
    EDIT_ALL_USERS = "EDIT_ALL_USERS",
    ADD_BOOKS = "ADD_BOOKS",
    EDIT_BOOKS = "EDIT_BOOKS",
    REMOVE_BOOKS = "REMOVE_BOOKS",
}