openapi: "2.0"
servers:
  - url: http://localhost:8080/api/v1
paths:
  /book:
    post:
      tags:
        - "BOOK"
      summary: "Create book"
      description: "Create book"
      operationId: "createBook"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            properties:
              authorId:
                type: "number"
                required: false
              title:
                type: "string"
              publisher:
                type: "string"
      responses:
        201:
          description: "Successful"
        400:
          description: "Something went wrong"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
  /book/{id}:
    put:
      tags:
        - "BOOK"
      summary: "Edit book"
      description: "Edit book"
      operationId: "editBook"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "Book ID"
          required: true
          type: "number"
        - in: "body"
          name: "body"
          required: true
          schema:
            properties:
              authorId:
                type: "number"
                required: false
              title:
                type: "string"
                required: false
              publisher:
                type: "string"
                required: false
    responses:
        200:
          description: "Successful"
        400:
          description: "Something went wrong"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
    delete:
      tags:
        - "BOOK"
      summary: "Delete book"
      description: "Delete book by id"
      operationId: "deleteBook"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "Book ID"
          required: true
          type: "number"
      responses:
        200:
          description: "Successful"
        400:
          description: "Something went wrong"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"